### PR TITLE
Fix: Stilton cheese returns true

### LINKED ISSUE #32: Stilton cheese returns true

### PR DESCRIPTION
**Pull request by gianantoniopini**
Modified the isVeganIngredient function to return false if all ingredient words are in non-vegan list.
Added "Stilton" to the non-vegan list.
Resolves #32

### CODE REVIEW

**Comment by hmontazeri** [comment]
@gianantoniopini  thanks for the PR. Could you please also add a separate test where its returning true for example for 'soy cheese'.

**Comment by gianantoniopini** [comment]
@hmontazeri thanks, just added the separate test for 'soy cheese'

**Comment by gianantoniopini** [comment]
Resolves #32

**Comment by hmontazeri** [comment]
one last thing: https://travis-ci.org/github/hmontazeri/is-vegan/jobs/678140594

CI is failing, it's just a syntax issue. Thanks

**Comment by gianantoniopini** [comment]
Sorry about the CI build failing, I am having a look at this.

**Comment by gianantoniopini** [comment]
@hmontazeri I have just committed the change to fix the eslint error causing CI build to fail.

**Comment by hmontazeri** [comment]
Nice! Merging....

**Pull request merged**
