### PR TITLE
Add support for ingredients in Italian

### LINKED ISSUE #14: Make it multilingual
Make it multilingual

### PR DESCRIPTION
**Pull request by gianantoniopini**
Added first version of ingredients .json files in Italian ('it') and new function to set the ingredients language.
In order to add support for more languages in the future, the ingredients .json files will need to be added under the i18n directory, as already done for 'it'.

Resolves #14

### CODE REVIEW

**Comment by gianantoniopini** [comment]
@hmontazeri Can you please have a look at this pull request ?

**Comment by hmontazeri** [comment]
sure @gianantoniopini  as soon as I find a free minute. Thanks for the PR.

**Comment by gianantoniopini** [comment]
@hmontazeri Hi Hamed, thanks.

**Comment by hmontazeri** [comment]
@gianantoniopini do we really need the dependency to validate.js?

**Comment by gianantoniopini** [comment]
@hmontazeri Regarding the dependency to validate.js. Currently it is used in the new setIngredientsLanguage function to perform basic validation when setting a new ingredients language. I thought it might be a good idea to sort of "delegate" the validation to this package. But we could also remove this dependency and implement the validation code ourselves, if you think it might be better.

**Comment by hmontazeri** [comment]
I’d rather have no dependency to other packages if not really necessary... so I’d recommend we do it ourself as it’s just a basic validation if language is set or not. Do you agree?

**Comment by gianantoniopini** [comment]
Yes, i understand. I will move the validation implementation to our package and remove the dependency to validate.js . It should be a simple change.

**Comment by gianantoniopini** [comment]
@hmontazeri Just committed the change to remove the dependency to validate.js

**Comment by hmontazeri** [comment]
Checking it! Getting back to you soon. Thanks

**Comment by hmontazeri** [comment]
Looks good to time @gianantoniopini. Thanks for the effort 👍

**Pull request merged**
